packages:
- skylighting-core
- skylighting
extra-deps:
- git: https://github.com/jgm/xml
  subdir: xml-conduit
  commit: 2274b3c26fda7406337ce47cdfd862ef187694e2
resolver: lts-14.6
ghc-options:
    "$locals": -optP-Wno-nonportable-include-path
