packages:
- skylighting-core
- skylighting
extra-deps:
- git: https://github.com/snoyberg/xml
  subdir: xml-conduit
  commit: 4be1021791dcdee8b164d239433a2043dc0939ea
resolver: lts-14.6
ghc-options:
    "$locals": -optP-Wno-nonportable-include-path
